// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: online.proto

#include "online.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace im {
namespace proto {
PROTOBUF_CONSTEXPR Online::Online(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.users_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OnlineDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OnlineDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OnlineDefaultTypeInternal() {}
  union {
    Online _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OnlineDefaultTypeInternal _Online_default_instance_;
}  // namespace proto
}  // namespace im
static ::_pb::Metadata file_level_metadata_online_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_online_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_online_2eproto = nullptr;

const uint32_t TableStruct_online_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::im::proto::Online, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::im::proto::Online, _impl_.users_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::im::proto::Online)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::im::proto::_Online_default_instance_._instance,
};

const char descriptor_table_protodef_online_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014online.proto\022\010im.proto\032\nuser.proto\"\'\n\006"
  "Online\022\035\n\005users\030\001 \003(\0132\016.im.proto.UserB$\n"
  "\025com.zhuzichu.protocolB\013OnlineProtob\006pro"
  "to3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_online_2eproto_deps[1] = {
  &::descriptor_table_user_2eproto,
};
static ::_pbi::once_flag descriptor_table_online_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_online_2eproto = {
    false, false, 123, descriptor_table_protodef_online_2eproto,
    "online.proto",
    &descriptor_table_online_2eproto_once, descriptor_table_online_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_online_2eproto::offsets,
    file_level_metadata_online_2eproto, file_level_enum_descriptors_online_2eproto,
    file_level_service_descriptors_online_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_online_2eproto_getter() {
  return &descriptor_table_online_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_online_2eproto(&descriptor_table_online_2eproto);
namespace im {
namespace proto {

// ===================================================================

class Online::_Internal {
 public:
};

void Online::clear_users() {
  _impl_.users_.Clear();
}
Online::Online(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:im.proto.Online)
}
Online::Online(const Online& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Online* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.users_){from._impl_.users_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:im.proto.Online)
}

inline void Online::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.users_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Online::~Online() {
  // @@protoc_insertion_point(destructor:im.proto.Online)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Online::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.users_.~RepeatedPtrField();
}

void Online::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Online::Clear() {
// @@protoc_insertion_point(message_clear_start:im.proto.Online)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.users_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Online::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .im.proto.User users = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_users(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Online::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:im.proto.Online)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .im.proto.User users = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_users_size()); i < n; i++) {
    const auto& repfield = this->_internal_users(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:im.proto.Online)
  return target;
}

size_t Online::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:im.proto.Online)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .im.proto.User users = 1;
  total_size += 1UL * this->_internal_users_size();
  for (const auto& msg : this->_impl_.users_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Online::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Online::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Online::GetClassData() const { return &_class_data_; }


void Online::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Online*>(&to_msg);
  auto& from = static_cast<const Online&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:im.proto.Online)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.users_.MergeFrom(from._impl_.users_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Online::CopyFrom(const Online& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:im.proto.Online)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Online::IsInitialized() const {
  return true;
}

void Online::InternalSwap(Online* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.users_.InternalSwap(&other->_impl_.users_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Online::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_online_2eproto_getter, &descriptor_table_online_2eproto_once,
      file_level_metadata_online_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace im
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::im::proto::Online*
Arena::CreateMaybeMessage< ::im::proto::Online >(Arena* arena) {
  return Arena::CreateMessageInternal< ::im::proto::Online >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
